### ISSUE TITLE
Unrecognized function F_Tran

### ISSUE THREAD

**Issue by slhck** [TranHuyen1191/CQM#2]
I am trying to run the main function, but this code seems to be missing the entire folder "CQMFunction."

When I run the example from the README, I get:

![image](https://user-images.githubusercontent.com/582444/155739680-47ee3b82-a894-43ce-82f3-328819db0293.png)

I just sourced the main `F_CQM.m` file and ran the example command.

Is there anything else I need to do?

**Comment by slhck** [comment]
I solved it by moving all functions from the `function` folder to the same folder as the main `F_CQM` function, and removing the line with `addpath(genpath([pwd slash 'CQMFunction']))`. Perhaps this line could also be changed to use `function` instead of `CQMFunction`.  I have not really used MATLAB before, so maybe you know the best solution.

**Comment by TranHuyen1191** [comment]
`addpath(genpath([pwd slash 'CQMFunction']))` is to add folders to search paths. 
So it can search for functions in the folders. 
I use different slashes for different OS. 
`if ismac; slash = '/'; else slash = '\'; end;`
Maybe you should change `slash` based on your OS. 
But, I think your solution is also fine.

**Comment by slhck** [comment]
The problem is not with the slashes. The code uses "CQMFunction", but the folder is called "function". So you would need to change it.

Perhaps you could make this fix. It would help in case others would like to run the code. Thanks!

**Comment by TranHuyen1191** [comment]
I have fixed it. 
Thanks!

**Comment by slhck** [comment]
Thank you!
