### ISSUE TITLE
Output is discrete – is it expected?

### ISSUE THREAD

**Issue by slhck** [TranHuyen1191/CQM#3]
I have a question regarding the expected output of the model. I find that it is outputting discrete scores, i.e. 3.2, 4, 4.2 — nothing in between.

I am calling the model exactly as specified in the README, using a different value for initial loading, and different sets of video scores, coming directly from P.1203.1.

I am using the last score of the function output (i.e. `end(…)` in MATLAB) to get the "final" score for each sequence. I noticed I am getting only 25 distinct output values for a set of over 1000 audiovisual sequences. Is this expected, or am I doing something wrong?

The original subjective MOS distribution is like this:

![image](https://user-images.githubusercontent.com/582444/156173513-55083b60-e202-477e-a380-831cd834b790.png)

From the CQM model, I get this distribution:

![image](https://user-images.githubusercontent.com/582444/156173553-12c2b9e3-a2c0-4c74-85b6-1bf38033b538.png)

(Note that the O46 in the below figure is just for comparison purposes … it is the CQM result.)

**Comment by TranHuyen1191** [comment]
<img width="732" alt="Screen Shot 2022-03-02 at 20 42 04" src="https://user-images.githubusercontent.com/7641968/156355457-681c47f6-7226-4fd8-aa1b-f55ca46aef3a.png">

I tried extracting the last scores for some different examples, and they are continuous.
Could you give me some examples of your sequences?

**Comment by slhck** [comment]
Sure, I have a CSV file containing various individual sequences:

![image](https://user-images.githubusercontent.com/582444/156357307-cb7df4b9-b0cc-4495-9e6d-8958ae5d6e90.png)

I am using the following code to calculate the values for each row in the CSV file:

```
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["db_id", "device", "video", "ild", "p_buff", "l_buff", "pvs_id"];
opts.VariableTypes = ["categorical", "categorical", "string", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["video", "p_buff", "l_buff", "pvs_id"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["db_id", "device", "video", "p_buff", "l_buff", "pvs_id"], "EmptyFieldRule", "auto");

% Import the data
data = readtable("test.csv", opts);


%% Clear temporary variables
clear opts

output_sz = [height(data) 4];
output_vartypes = ["string","string","string","double"];
output_varnames = ["model","pvs_id","device","O46"];
output_table = table('Size',output_sz,'VariableTypes',output_vartypes,'VariableNames',output_varnames)

for row = 1:height(data) 
    pvs_id = data{row,"pvs_id"};
    o22 = jsondecode(data{row, "video"});
    ild = data{row, "ild"};
    p_buff = jsondecode(data{row, "p_buff"});
    l_buff = jsondecode(data{row, "l_buff"});
    device = data{row, "device"};
    model = "CQM";
    ret = F_CQM(ild, o22, p_buff, l_buff);
    O46 = ret(end);
    output_table(row,:) = {model, pvs_id, device, O46};
end

writetable(output_table, "output.csv")
```

Here is a test file containing only one row.

[test.csv](https://github.com/TranHuyen1191/CQM/files/8169387/test.csv)

I just noticed I am calling `ret = F_CQM(ild, o22, p_buff, l_buff)` without the `[2, 4]` parameter.

When I add it, I get this:

```
>> F_CQM(ild, o22, p_buff, l_buff, [2,4])    
SWITCH expression must be a scalar or a character vector.

Error in F_CQM (line 71)
        switch wqModel %% Calculate instant window quality value
```

**Comment by TranHuyen1191** [comment]
Actually, you do not need to add [2,4]. It is already l_buff in your code. 
I think the problem here is related to o22. 
Please try `F_CQM(ild, o22.', p_buff, l_buff)` 
`o22.'` is the transpose of o22

**Comment by slhck** [comment]
Thank you, I will be trying this. And I do not need to transpose the p_buff, l_buff scores? They are read in the same way as O22, and there might be multiple entries for each of the variables.

**Comment by slhck** [comment]
I was able to solve it with the transposing of p_buff and l_buff, too. Thank you for the help!
